### ISSUE TITLE
Does this library run on API 19.. 

### ISSUE THREAD

**Issue by AndroPlus** [mars885/persistentsearchview#2]
Hi, 
Currently it run only on API 21,  I used tools:overrideLibrary="com.paulrybitskyi.persistentsearchview" 
to make it run on API  19.. Will it run smoothly on API 19 devices .. without error ?

**Comment by mars885** [comment]
@AndroPlus Hi. Currently the minimum library API is 21. As for overriding the min API version to 19,
you have to be careful since on pre-Lollipop devices I've encountered a weird error when testing on the emulator where `onRestoreInstanceState` method throws IllegalArgumentException, so I'd not recommend changing the min API version to those lower of Lollipop.

**Comment by mars885** [comment]
Closing it for now.
