### ISSUE TITLE
unable to scrool suggestion only in fragment

### ISSUE THREAD

**Issue by daya-pangestu** [mars885/persistentsearchview#4]
hi, i'm facing weird issue when placing searchivew on fragment, suggestion work as i expected but unable to scroll. i've also confirmed with the same code, sugestion can be scrolled flawlesly

**Comment by mars885** [comment]
Hello. Could you create a repository demonstrating the problem and provide us with a link to it?

**Comment by daya-pangestu** [comment]
the fragment
https://github.com/daya-pangestu/simple_dictionary/blob/master/app/src/main/java/com/daya/dictio/view/FSearch.java

activity
https://github.com/daya-pangestu/simple_dictionary/blob/master/app/src/main/java/com/daya/dictio/view/SearchActivity.java

both of fragment and activity use code like you provided

**Comment by mars885** [comment]
It looks like the issue is resolved if you replace `CoordinatorLayout` with a `RelativeLayout` inside [this](https://github.com/daya-pangestu/simple_dictionary/blob/master/app/src/main/res/layout/fragment_fsearch_layout.xml) XML file. CoordinatorLayout prohibits you from scrolling the suggestions container for some very odd reason.

I've also found similar issues of other search view libraries. For example, see [this](https://github.com/MiguelCatalan/MaterialSearchView/issues/154) and [this](https://github.com/MiguelCatalan/MaterialSearchView/issues/90) issue of the MaterialSearchView library. Its users also raised similar questions regarding the CoordinatorLayout blocking the scrolling. 

You can also find a bunch of different solutions on how to fix this problem in the issues I've linked, so let me know if that helps.

**Comment by daya-pangestu** [comment]
thanks..., after i change Coordinatorlayout to relative everything works as i expected
your library indeed was amazing
