### ISSUE TITLE
Unable to extract title of SuggestionItem from SuggestionItem object.

### ISSUE THREAD

**Issue by prezrohit** [mars885/persistentsearchview#7]
I am using mars885 Persistent Search View. I dont know how to extract the SuggestionItem title from its object. I want to extract the title in a string and use it to show some results. i encountered this problem while using setOnSuggestionChangeListener -> onSuggestionPicked(). 

I am a Java Programmer

**Comment by mars885** [comment]
Hello. Thanks for reporting it. I'll check this out this week and notify you about results.

**Comment by mars885** [comment]
Hello. 

Sorry for such a late reply. I totally forgot about it.

In order to extract text from a suggestion, you need to call `getItemModel()` method on the object passed through onSuggestionPicked() listener. It provides you an instance of the [Suggestion](https://github.com/mars885/persistentsearchview/blob/master/persistentsearchview/src/main/java/com/paulrybitskyi/persistentsearchview/model/Suggestion.java) model class. Finally, you can access the text by calling [getText()](https://github.com/mars885/persistentsearchview/blob/master/persistentsearchview/src/main/java/com/paulrybitskyi/persistentsearchview/model/Suggestion.java#L138) method on the retrieved model instance.

See the sample project for more details how to use this library. Specifically, check out [this](https://github.com/mars885/persistentsearchview/blob/master/sample/src/main/java/com/paulrybitskyi/sample/DemoActivity.kt#L300) line. It shows how to retrieve the text from the picked item.
